# Basic config
whitelist-enabled: true

whitelist-existing-players: false
inherit-default-whitelist: false

database:
  type: mysql
  host: localhost
  port: 3306
  prefix: lw__
  database: database
  username: username
  password: password

# Enable/Disable the plugin entirely
enabled: true

# Ignore this config (the following options are not ignored)
ignore: false

# Logging level
logging: info

# Enable test mode
test: false
